# Generated by Django 4.0.3 on 2022-03-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog-img.png', upload_to='post/imges/'),
        ),
    ]
